import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* House character sprite (top-right). Consider renaming file to house_idle.png later */}
        <div className="pixel-art house-sprite">
          <Image
            src="/assets/sprites/Investy - Resting-1.png.png"
            alt="The House"
            fill
            className="object-contain"
            priority
          />
        </div>
        {children}
      </body>
    </html>
  );
}
